/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.GlobalClass;
import Controladores.MovimientoJpaController;
import Controladores.ProductoJpaController;
import Controladores.ProductoMovimientoJpaController;
import Entidades.Movimiento;
import Entidades.Producto;
import Entidades.ProductoMovimiento;
import Entidades.Usuario;
import java.awt.Desktop;
import java.awt.Rectangle;
import java.io.File;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author warriors
 */
public class reporte_compras extends javax.swing.JFrame {

    MovimientoJpaController controlmovimiento = new MovimientoJpaController();
    ProductoMovimientoJpaController controlproductoM = new ProductoMovimientoJpaController();
    DefaultTableModel modeloCarrito;
    List<Movimiento> listaMovimiento;
    List<ProductoMovimiento> listaProductoMovimiento;
    List<Producto> listaProducto;
    DefaultTableModel modelo;
    double compratotal=0;
    private final String ruta = System.getProperties().getProperty("user.dir");

    public reporte_compras() {
        initComponents();
        LlenarTabla();
        txtgenerando.setVisible(false);
        Progressbar_entradas.setVisible(false);
        setTitle("EasyStock");
        setResizable(false);
        setLocationRelativeTo(null);
        compratotal=calcularTotalCompras();
        txtcompras.setText(String.valueOf(compratotal));
        txtcompras.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReportecompras = new javax.swing.JTable();
        btn_reporte = new javax.swing.JButton();
        Progressbar_entradas = new javax.swing.JProgressBar();
        txtgenerando = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcompras = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reporte de Entradas");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaReportecompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Compra", "Fecha", "Descripcion_compra", "ID_remitente", "Vendedor", "Tipo_Movimiento", "ID_Producto", "Descripcion_producto", "Cantidad", "Unidad_medida", "Valor_venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaReportecompras);
        tablaReportecompras.getTableHeader().setReorderingAllowed(false) ;

        btn_reporte.setText("Generar Reporte");
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });

        txtgenerando.setText("Generando:");

        jLabel1.setText("Valor de compras totales:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtgenerando, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Progressbar_entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 315, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcompras, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Progressbar_entradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgenerando))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (GlobalClass.usuario != null) {

            if (GlobalClass.usuario.getRol().equalsIgnoreCase("Administrador")) {
                InicioAdministrador i = new InicioAdministrador();
                i.setVisible(true);
                this.dispose();
            } else {
                InicioVendedor i = new InicioVendedor();
                i.setVisible(true);
                this.dispose();
            }

        } else {
            InicioAdmonSupremo i = new InicioAdmonSupremo();
            i.setVisible(true);
            this.dispose();

        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public double calcularTotalCompras() {

        for (int i = 0; i < tablaReportecompras.getRowCount(); i++) {
            compratotal += (Double) tablaReportecompras.getValueAt(i, 10);
        }
        return compratotal;
    }

    public void generarExcel() {

        try {
            if (tablaReportecompras.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No hay reportes de Compras en la Tabla");
            } else {
                Thread t = new Thread() {
                    public void run() {
                        XSSFWorkbook workbook = new XSSFWorkbook();
                        XSSFSheet hoja = workbook.createSheet();

                        txtgenerando.setVisible(true);
                        Progressbar_entradas.setVisible(true);

                        XSSFRow fila = hoja.createRow(0);
                        fila.createCell(0).setCellValue("ID");
                        fila.createCell(1).setCellValue("Fecha_Compra");
                        fila.createCell(2).setCellValue("Descripcion");
                        fila.createCell(3).setCellValue("ID_Remitente");
                        fila.createCell(4).setCellValue("Vendedor");
                        fila.createCell(5).setCellValue("Tipo_movimiento");
                        fila.createCell(6).setCellValue("ID_Producto");
                        fila.createCell(7).setCellValue("Descripcion");
                        fila.createCell(8).setCellValue("Cantidad");
                        fila.createCell(9).setCellValue("Unidad_Medida");
                        fila.createCell(10).setCellValue("Valor_Venta");
                        fila.createCell(11).setCellValue("Valor_Compras_totales");

                        Progressbar_entradas.setMaximum(tablaReportecompras.getRowCount());
                        XSSFRow filas;
                        Rectangle rect;
                        for (int i = 0; i < tablaReportecompras.getRowCount(); i++) {
                            rect = tablaReportecompras.getCellRect(i, 0, true);
                            try {
                                tablaReportecompras.scrollRectToVisible(rect);
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "Error " + e);
                            }
                            tablaReportecompras.setRowSelectionInterval(i, i);
                            Progressbar_entradas.setValue((i + 1));

                            filas = hoja.createRow((i + 1));
                            filas.createCell(0).setCellValue(tablaReportecompras.getValueAt(i, 0).toString());
                            filas.createCell(1).setCellValue(tablaReportecompras.getValueAt(i, 1).toString());
                            filas.createCell(2).setCellValue(tablaReportecompras.getValueAt(i, 2).toString());
                            filas.createCell(3).setCellValue(tablaReportecompras.getValueAt(i, 3).toString());
                            filas.createCell(4).setCellValue(tablaReportecompras.getValueAt(i, 4).toString());
                            filas.createCell(5).setCellValue(tablaReportecompras.getValueAt(i, 5).toString());
                            filas.createCell(6).setCellValue(tablaReportecompras.getValueAt(i, 6).toString());
                            filas.createCell(7).setCellValue(tablaReportecompras.getValueAt(i, 7).toString());
                            filas.createCell(8).setCellValue(tablaReportecompras.getValueAt(i, 8).toString());
                            filas.createCell(9).setCellValue(tablaReportecompras.getValueAt(i, 9).toString());
                            filas.createCell(10).setCellValue(tablaReportecompras.getValueAt(i, 10).toString());
                        }
                         filas=hoja.createRow(10);
                        filas.createCell(11).setCellValue(compratotal);

                        Progressbar_entradas.setString("Abriendo Excel...");
                        try {
                            workbook.write(new FileOutputStream(new File(ruta + "//reporteEntrada.xlsx")));
                            Desktop.getDesktop().open(new File(ruta + "//reporteEntrada.xlsx"));
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, " Error" + e);
                        }
                    }

                };
                t.start();
            }

        } catch (Exception e) {
        }

    }


    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
        generarExcel();


    }//GEN-LAST:event_btn_reporteActionPerformed

    public void LlenarTabla() {
        String UsuarioTrans;
        String cliente;
        listaMovimiento = controlmovimiento.findMovimientoEntities();
        listaProductoMovimiento = controlproductoM.findProductoMovimientoEntities();
        DefaultTableModel modelo = (DefaultTableModel) tablaReportecompras.getModel();
        if (listaMovimiento != null && listaProductoMovimiento != null) {
            for (Movimiento obj : listaMovimiento) {
                for (ProductoMovimiento obj1 : listaProductoMovimiento) {
                    if (obj.getId() == obj1.getIdMov().getId() && (obj.getTipoMov().equalsIgnoreCase("Compra") || obj.getTipoMov().equalsIgnoreCase("PrestamoEntrada")
                            || obj.getTipoMov().equalsIgnoreCase("DevolucionEntrada"))) {
                        if (obj.getUsuarioTrans() == null) {
                            UsuarioTrans = "Admin";
                        } else {
                            UsuarioTrans = obj.getUsuarioTrans().getNombre();
                        }

                        modelo.addRow(new Object[]{obj1.getId(), obj.getFechaMovimiento(), obj.getDescripcion(), obj.getIdRemitente(),
                            UsuarioTrans, obj.getTipoMov(), obj1.getIdProducto().getId(),
                            obj1.getIdProducto().getDescripcion(), obj1.getCantTrans(), obj1.getIdProducto().getUnidadMedida(), obj1.getValorTrans()});
                    } else {

                    }

                }

            }

        } else {
            JOptionPane.showMessageDialog(null, "Tablas sin registros");
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporte_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporte_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporte_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporte_compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporte_compras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progressbar_entradas;
    private javax.swing.JButton btn_reporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReportecompras;
    private javax.swing.JTextField txtcompras;
    private javax.swing.JLabel txtgenerando;
    // End of variables declaration//GEN-END:variables
}
